### ISSUE TITLE
Bad version in installation docs

### ISSUE THREAD

**Issue by andreichirkunovgoon** [malcommac/SwiftDate#183] opened 2016-03-20 13:49 UTC
let date2 = NSDate(year: 2015, month: 12, day: 25, hour: 14) 

gives an error. I installed using pods. Is this issue known to you? The other example, 

let date1 = "2015-01-05T22:10:55.200Z".toDate(DateFormat.ISO8601)

works well. Thank you in advance for your reply!

**Comment by Hout** [comment] 2016-03-20 14:58
```
let date2 = NSDate(year: 2015, month: 12, day: 25, hour: 14) 
print(date2)
```
Shows: `2015-12-25 13:00:00 +0000`. (Please note that it runs in the CET time zone, so this is correct)

I.e. unable to reproduce...

**Comment by Hout** [comment] 2016-03-20 14:59
Which version of the pod do you use?

**Comment by andreichirkunovgoon** [comment] 2016-03-20 18:15
I used v 2.0.2, which was specified in the installation guide. I didn't check for newer versions. I now updated to v3 and it works. Thank you for your hint! You did amazing code!!

**Comment by Hout** [comment] 2016-03-21 07:27
Thx for the feedback.

I will correct the version in the installation guide.

**Comment by Hout** [comment] 2016-03-21 12:17
Fixed in 3.0.9

**Closed by Hout** 2016-03-21 12:17 UTC
Labels: bug, documentation
