### ISSUE TITLE
Version 5.0.0  does not support Linux

### ISSUE THREAD

**Issue by Antonasg** [malcommac/SwiftDate#590] opened 2018-09-14 06:51 UTC
Specifically because of:  
`import ObjectiveC.runtime` 
In `AssociatedValues.swift` 

It should be stated clearly in the Readme if the plan is to no longer support Linux by using the ObjectiveC runtime.

**Comment by malcommac** [comment] 2018-09-18 21:09
Duplicate of #568 
Currently I'm working to restore it by disabling the Objective-C Runtime dependency.

**Closed** 2018-09-18 21:09 UTC
Labels: duplicate
