### ISSUE TITLE
Wrong display on actual device

### ISSUE THREAD

**Issue by kalwyn** [malcommac/SwiftDate#28] opened 2015-08-07 22:40 UTC
On simulator, I am getting the proper display of about 1 day ago.

Upon moving to the device, I am getting the wrong display of about 9.223372e+18 wks ago.

**Comment by malcommac** [comment] 2015-08-17 17:34
Hi,
Can you paste here your code? thanks

**Comment by kalwyn** [comment] 2015-08-17 18:02
```` swift
var postedOn = post.createdAt!
post["timeAgo"] = postedOn.toRelativeString(fromDate: NSDate(), abbreviated: true, maxUnits: 1)
````

post.createdAt looks like this: 2015-08-07T16:39:44.703Z

**Comment by kalwyn** [comment] 2015-08-17 18:04
Top right

![image](https://cloud.githubusercontent.com/assets/8174087/9312115/9fcf458c-44cf-11e5-925b-a160fbe18252.jpg)

**Comment by kalwyn** [comment] 2015-08-17 18:04
Top right
![image](https://cloud.githubusercontent.com/assets/8174087/9312155/c2d5bb7e-44cf-11e5-9bc3-c130664c516d.jpg)

**Comment by malcommac** [comment] 2015-08-17 19:41
Are you using SwiftDate from CocoaPods?

**Comment by kalwyn** [comment] 2015-08-17 19:57
Yes.

**Comment by malcommac** [comment] 2015-08-17 20:15
It should be an outdated version compared to the master one and this error should be a duplicate of this: https://github.com/malcommac/SwiftDate/issues/15.
However at this time I can't update cocoapods version with a new 1.0.11 build due to a GitHub's API error (I'll try to do it later today); however if you want to test, try to download the master release package and use it; everything should be ok.

**Comment by kalwyn** [comment] 2015-08-17 20:29
Will do this later today when I'm off work. Thanks for the response.

**Comment by malcommac** [comment] 2015-08-18 07:53
Just posted 1.0.11 to cocoapods

**Comment by kalwyn** [comment] 2015-08-18 18:08
Works like a charm, thanks!

**Comment by malcommac** [comment] 2015-08-18 19:25
Thanks for your report

**Closed by malcommac** 2015-08-18 19:25 UTC
